### ISSUE TITLE
python 提交判定后RE 错误

### ISSUE THREAD

**Issue by oumingyang** [acmcodercom/ojhtml#1]
python3, 练习的时候 使用自测数据在 平台编译可以AC,但提交判定之后就是RE。为了定位原因，使用文档参考代码提交线上判定的时候也会出现 Runtime Err 这个原因是什么呢。
#!/usr/bin/env python  
#coding=utf-8  
while 1:
    a=[]  
    s = input()
    if s != "":
        for x in s.split():
            a.append(int(x))
        print(sum(a))
    else:
        break

**Comment by lifubang** [comment]
好的，收到，给你带来的不便深感抱歉。

练习模式我们正在开发中。在练习模式上线之前，你可以使用“自测数据”进行Runtime Error的查看，前提是你需要自己构造测试用例。

**Comment by oumingyang** [comment]
使用自测数据的时候是 AC，提交判定就是RE，我调试了一下，问题出现在 输入这里，但是不知道为啥使用自测数据没有问题，但是提交判定会出现RE。然后使用官方文档提供的 输入示例代码也是RE，有点懵逼

**Comment by lifubang** [comment]
哪一个题目？

**Comment by oumingyang** [comment]
> 哪一个题目？

https://labfiles.acmcoder.com/ojhtml/index.html#/?id=%e7%a4%ba%e4%be%8b%e4%bb%a3%e7%a0%81-11 赛码上的联系题用Python写都这样。输入参考链接里给的 python3的代码

**Comment by oumingyang** [comment]
相同的场景我用 java的示例代码都可以正常运行，只是AW，输出错了。但是Python3这个就奇怪了。

**Comment by lifubang** [comment]
但是你把这个代码复制到哪个题目中去运行呢？不是所有的题目都是a+b

**Comment by oumingyang** [comment]
相同的场景我用 java的示例代码都可以正常运行，只是AW，输出错了。但是Python3这个就奇怪了。

**Comment by oumingyang** [comment]
> 但是你把这个代码复制到哪个题目中去运行呢？不是所有的题目都是a+b

这个无非就是AW，不应该是RE呀

**Comment by lifubang** [comment]
我明白了，python没有eof，所以必须写try except，但是这么写很多考生都不太愿意，所以我们在oj里面作了处理，如果你的答案对了，我们会忽略eof error，如果你的答案是错的，会显示runtime error。

**Comment by oumingyang** [comment]
> 我明白了，python没有eof，所以必须写try except，但是这么写很多考生都不太愿意，所以我们在oj里面作了处理，如果你的答案对了，我们会忽略eof error，如果你的答案是错的，会显示runtime error。

这样没法调试了

**Comment by lifubang** [comment]
```python
#!/usr/bin/env python
# coding=utf-8
while 1:
    a = []
    s = input()
    if s != "":
        for x in s.split():
            a.append(int(x))

        print(2) #你可以把这里改成样例的答案试试，会看到通过了一部分。
    else:
        break

```

**Comment by lifubang** [comment]
> 这样没法调试了

好，我们想想如何再改进下。多谢你的建议。

**Comment by oumingyang** [comment]
> ```python
> #!/usr/bin/env python
> # coding=utf-8
> while 1:
>     a = []
>     s = input()
>     if s != "":
>         for x in s.split():
>             a.append(int(x))
> 
>         print(2) #你可以把这里改成样例的答案试试，会看到通过了一部分。
>     else:
>         break
> ```

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/29618441/173187247-7677456e-353d-4994-95da-f7b10a87e01c.png">

然而并不会哦，依然100% RE

**Comment by lifubang** [comment]
这个是两行的，你输出的是
```
5
5
```
所以肯定是错误的。
你可以找个单行的题目试试，或者你加一个行数计数变量，当其为第二行时输出5。

**Comment by lifubang** [comment]
```python
#!/usr/bin/env python
# coding=utf-8
line = 1
while 1:
    a = []
    s = input()
    if s != "":
        line = line+1
        for x in s.split():
            a.append(int(x))
        if line == 2:
            print(5) #你可以把这里改成样例的答案试试，会看到通过了一部分。
    else:
        break
```

**Comment by oumingyang** [comment]
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/29618441/173187490-f0c1da82-3b45-486d-b4ca-a994205036c5.png">
<img width="1786" alt="image" src="https://user-images.githubusercontent.com/29618441/173187508-02981e6c-f359-4057-acda-9a7fff69d898.png">
我理解 我直接 循环外输出 5也应该是 部分通过吧

**Comment by oumingyang** [comment]
> ```python
> #!/usr/bin/env python
> # coding=utf-8
> line = 1
> while 1:
>     a = []
>     s = input()
>     if s != "":
>         line = line+1
>         for x in s.split():
>             a.append(int(x))
>         if line == 2:
>             print(5) #你可以把这里改成样例的答案试试，会看到通过了一部分。
>     else:
>         break
> ```

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/29618441/173187610-ac81a427-3b18-42e1-8b67-dbe586d86f62.png">
我好像理解你们这个平台了，它要求在 while 循环里就把每个答案输出来，要支持 连续输入不同的测试用例。我猜的对吗？这样的话 使用自测数据是打死也不会知道问题出在哪里的。

**Comment by oumingyang** [comment]
https://discuss.acmcoder.com/topic/5d47dfa8b99ad44605a1700b 老哥我们这个网站是不是不能登录发言了？

**Comment by lifubang** [comment]
> https://discuss.acmcoder.com/topic/5d47dfa8b99ad44605a1700b 老哥我们这个网站是不是不能登录发言了？

已经不能了，只能浏览了。C端我们正在努力开发中。

**Comment by lifubang** [comment]
我基本知道问题在哪里了，我们最近会升级，让调试更人性化。

**Comment by lifubang** [comment]
@oumingyang 已经升级了，有空你可以再试试！
