### ISSUE TITLE
[JS] 从未见过如此恶劣的东西

### ISSUE THREAD

**Issue by GrinZero** [acmcodercom/ojhtml#2]
就这种破烂也敢拿出来？是不是没有人骂过你们

**Comment by RickDamon** [comment]
输出都不给人看一下。这种oj系统笔试啥时候能进步一下

**Comment by lifubang** [comment]
Sorry，考试分为自测模式和考试模式，自测模式时是可以看见输出的。考试模式如果能看到输出，那是不是会导致测试用例泄露呢？

**Comment by lifubang** [comment]
如下图，请查看“你的输出为”。

![image](https://user-images.githubusercontent.com/783424/185892487-6785abdd-c272-4d07-b349-3af6fa37513b.png)

**Comment by GrinZero** [comment]
1. jsv8，自测模式同样无法输出，我确定我在考试的时候输出不了，甚至打过电话询问
2. jsv8，你们实现的自定义输入输出在本地无法跑，也没有看到相关npm包

**Comment by lifubang** [comment]
> 1. jsv8，自测模式同样无法输出，我确定我在考试的时候输出不了，甚至打过电话询问

能否给出一段代码，我们可以看看，上面的截图是我真实的截图，是可以看到的。

> 2. jsv8，你们实现的自定义输入输出在本地无法跑，也没有看到相关npm包

编辑器的帮助文件中有提到( https://labfiles.acmcoder.com/ojhtml/index.html#/?id=jsv8 )，我们定制的v8代码。( https://github.com/acmcodercom/v8/tree/forstdio_baseon_6.2.340/samples )
如果需要本地调试，其实可以用nodejs，nodejs的输入输出稍微复杂些（ https://labfiles.acmcoder.com/ojhtml/index.html#/?id=nodejs ），最近我们会把类似jsv8的这种输入输出定制到nodejs包中去，具体可以在这里查看： https://www.npmjs.com/package/node-stdio
