### ISSUE TITLE
你们对自己的产品满意吗？？？

### ISSUE THREAD

**Issue by Heart-beatsss** [acmcodercom/ojhtml#3]
先不说风格样式太差劲了，就是连最起码的编程样例都不给一下？每次用你们的OJ就好多时间花在输入输出上
还有就是能不能自动填充测试样例？
学学牛客吧！！！牛客体验真的吊打赛码！旁边基本没人对你们的OJ有好感

**Comment by Heart-beatsss** [comment]
服了，笔试过程中，系统还崩了。。。

**Comment by howieyoung91** [comment]
这种输入输出方式是咋想出来的？？😅
