### ISSUE TITLE
你们产品做得一坨屎一样

### ISSUE THREAD

**Issue by JianmingLi-888** [acmcodercom/ojhtml#4]
输入输出做得一坨大便，谁他妈的笔试的时候看你那破文档在里面找啊？多给两个样例会死吗？
编译运行调试就跟我奶奶一行字一行字读写一样，你家没钱买服务器吗？编译一次要等15秒？
早点倒闭

**Comment by lifubang** [comment]
兄弟，我理解你的心情，但是放平心态，不要骂人，每次OJ考试，得高分的考生是很多的。
1、输入输出和OJ系统一点关系都没有，输入输出就是标准的命令行的输入输出，输入输出格式是客户自己定的，我个人感觉写的都比较明确；
2、15秒这个你说的我可以接受，的确有点长，我觉得可以减少或者有结果了就可以再点。但是我解释一下15秒的初衷，考生的下一次运行，应该是修改了代码才会运行，但是修改一次代码我们认为至少得有一段时间，不希望考生改一个代码就点一次，往往无法连续思考，陷入一个狂点的状态。当然，这个对快结束时的考生确实有点难受，可能就写错了一点点，改对了没准就对了，但是考生放心，只要你改了，考后都会自动重跑的。

**Comment by JianmingLi-888** [comment]
对不起，是我破防了
